"""empty message

Revision ID: 0976cf48d261
Revises: None
Create Date: 2018-02-21 03:18:35.193800

"""

# revision identifiers, used by Alembic.
revision = '0976cf48d261'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('spots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('spot_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('near_by_places', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('similar_places', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('special_attraction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('things_to_do', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_to_visit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('how_to_reach', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('spot_id', name='spots_pkey')
    )
    op.create_table('visits',
    sa.Column('place_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('place_id', name='visits_pkey')
    )
    # ### end Alembic commands ###
