"""empty message

Revision ID: 5f7cec86b845
Revises: 7b1d66baf65c
Create Date: 2018-02-26 12:31:12.047229

"""

# revision identifiers, used by Alembic.
revision = '5f7cec86b845'
down_revision = '7b1d66baf65c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blogs', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Blogs', 'keywords')
    # ### end Alembic commands ###
