"""empty message

Revision ID: a9123736678c
Revises: 0976cf48d261
Create Date: 2018-02-23 04:45:21.719583

"""

# revision identifiers, used by Alembic.
revision = 'a9123736678c'
down_revision = '0976cf48d261'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Postbirth', sa.Column('title', sa.String(), nullable=True))
    op.add_column('Prebirth', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Prebirth', 'title')
    op.drop_column('Postbirth', 'title')
    # ### end Alembic commands ###
